site_name: MyDevOps Docs
site_description: DevOps Learning Project
repo_url: https://github.com/ezdanapak/MyDevOps
docs_dir: docs
site_dir: site

theme:
  name: material

nav:
  - Home: index.md
  - Setup:
      - folder: setup/folder.md
      - Virtualbox Setup: setup/setup-virtualbox.md
      - Ubuntu Setup: setup/setup-ubuntu.md
      - MobaXterm Setup: setup/setup-mobaxterm.md
      
  - Tasks:
      - Task board: tasks/task.md
      - Task 1 VM: tasks/task1-vm.md
      - Task 2 Network: tasks/task2-network.md
      - Task 3: tasks/task3.md
      - Task 4: tasks/task4.md  
      - Task 5: tasks/task5.md
      - Task 6: tasks/task6.md
      - Task 7: tasks/task7.md
      - Task 8: tasks/task8.md
      - Task 9: tasks/task9.md
      - Task 10: tasks/task10.md
      - Task 11: tasks/task11.md
      - Task 12: tasks/task12.md
