site_name: MyDevOps Docs
site_description: DevOps Learning Project
repo_url: https://github.com/ezdanapak/MyDevOps
docs_dir: docs
site_dir: site

theme:
  name: material

nav:
  - Home: index.md
  - Setup:
      - Ubuntu Setup: setup/setup-ubuntu.md
      - Virtualbox Setup: setup/setup-virtualbox.md
  - Tasks:
      - Task board: tasks/task.md
      - Task 1 VM: tasks/task1-vm.md
      - Task 2 Network: tasks/task2-network.md
